### ISSUE TITLE
creacion de migraciones ( modelo usuario )

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#1]
se necesita crear el modelo de user de acuerdo al siguiente modelo

![Diagrama de clases actualizado](https://user-images.githubusercontent.com/30984939/79522414-9e88c780-8029-11ea-8568-94909e2b7a40.png)

**Comment by Martalf** [comment]
se crea migracion, seed y factory para usuarios de la api, queda a futuro la adecuacion de los mismos para el sistema de autenticación...
