### ISSUE TITLE
ajustar los estatus de las peticiones

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#10]
Se observa dentro de la aplicaicion, cuando se realiza una petición al api, no devuelve al navegador el status correcto. Por ejemplo, un usuario que se equivoca en el login debe devolver al navegador 400 o una peticion mal procesada un 422, un usuario que se vence el token 401. pero me arroja un 500.

#### Revisar los protocolos http que llegan del server y ajustarla para que lleguen con sus status correcto. 

![HTTP_status_codes](https://user-images.githubusercontent.com/30984939/90303729-79448280-de7e-11ea-8e49-5658fdff2927.gif)

**Comment by Martalf** [comment]
se ajustaron los codigos de respuesta http, falta el que manda laravel passport, que estoy viendo como lo modifico

**Comment by Martalf** [comment]
se ajusto el handling de la excepción autentication exception para manipular el json que se va a enviar a la vista... adicionalmente se uso un trait para crear responses personalizados... el mismo se irá llenando conforme vaya creciendo la app. Por favor bajar la version de la rama 9 para... probar los codigos de respuesta.
