### ISSUE TITLE
ajuste de campos de apiaudiophone_terms day events

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#12]
Se necesita cambiar el formato de salida del api de string de:

{
  apiaudiophoneterms_daysevents: "martes, miercoles, sabado"
}

a un array:

{
  apiaudiophoneterms_daysevents: [ "martes", "miercoles", "sabado" ]
}

debido a que tengo que separar, mapear ese campo, compararlos con los ya existentes  para luego asignaselos al check correspondiente en el proceso de recepcion de datos

![Uploading Captura de pantalla_2020-09-20_20-26-35.png…]()
.

**Comment by Martalf** [comment]
los cambios fueron realizados y actualizada la rama 9, por favor prueba si quieres que la presentación sea así... incluí todo el objeto que se mostraba como siempre massss.... el arreglo de dias de eventos como lo solicitaste

**Comment by Martalf** [comment]
revisalo y  me avisas... saludos mano... sigo con el tema de la excepcion del middleware...y ver como obtengo la fecha de expiración, avancé una parte pero aun falta.

**Comment by Martalf** [comment]
yo no se... si tu me pasaste el estudio de mercado de AWS y heroku?...
