### ISSUE TITLE
modulo de eventos: CRUD de eventos.

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#13]
![Captura de pantalla_2020-09-29_20-22-33](https://user-images.githubusercontent.com/30984939/94629863-f5a9ee00-0291-11eb-9f65-dfe687fd4305.png)

![Captura de pantalla_2020-09-29_20-23-23](https://user-images.githubusercontent.com/30984939/94629864-f6db1b00-0291-11eb-9e43-a9d00d39b9d9.png)

![Captura de pantalla_2020-09-29_20-24-04](https://user-images.githubusercontent.com/30984939/94629865-f773b180-0291-11eb-8ef6-7947153391e2.png)

El siguiente modulo es registro de eventos por el usuario, el objetivo es realizar el CRUD correspondiente al modulo. Atencion esta es una vista del usuario, no del administrador, accede con otro usuario con el status USER_ROLE, para que puedas ver la interacción.

**Comment by Martalf** [comment]
se crea crud del modelo eventos, por favor generar el issue para el modulo budget
