### ISSUE TITLE
crear endpoint de servicios

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#14]
se necesita la creacion de un metodo de consulta de la tabla apiaudiophone_services que ofrece la aplicación (GET) que retorne el nombre del servicio y id, son consumidos muy frecuentemente por los formularios al momento de seleccionar un servicio en day page y events page

**Comment by Martalf** [comment]
se crea la consulta a la tabla api-audiophoneservices y devuelve el id y la descripción del servicio, esta consulta se utiliza en el modulo de eventos  yterminos, recordemos que no existe modulo de control para la creación de servicios.
