### ISSUE TITLE
Eventos: Actualizar evento 

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#15]
Por favor revisar la peticion que realiza la actualizacion del evento, muestra un error 500 y no deja actualizar el evento

![Captura de pantalla_2020-12-02_21-57-15](https://user-images.githubusercontent.com/30984939/100953813-aed2b180-34e9-11eb-813b-c12cacbb2a89.png)
![Captura de pantalla_2020-12-02_21-56-51](https://user-images.githubusercontent.com/30984939/100953817-b003de80-34e9-11eb-9687-7df1df738dc5.png)
![Captura de pantalla_2020-12-02_21-56-31](https://user-images.githubusercontent.com/30984939/100953819-b09c7500-34e9-11eb-94a7-55a483b9fde2.png)

**Comment by Martalf** [comment]
se corrige actualización de eventos y estatus de eventos, eran dos variables no definidas.
