### ISSUE TITLE
Ajuste de requerimientos de la aplicación

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#16]
Ajustes y requerimientos de alcance de la aplicación:

1.- Audiophone core solo sera utilizado por administradores, ajustar el login para que solo permita el acceso al usuario admin, se dejara el modulo del usuario no pero no estara disponible para ellos. 

2.- El registro del usuario ya no estará disponible desde login sino desde la pantalla de users en admin y por defecto sera ese mismo rol.

3.- El admin tiene el control completo de los terminos, eventos y presupuesto.

**Comment by Martalf** [comment]
se adecuó el login controller para que solo permitiera otorgar acceso a los administradores

al controlador de terms no se le realizaron adecuaciones porque desde un inicio fue concebido para los administradores.

a los controllers de budgets, items y events tiene validaciones en cada método para que solo trabaje con usuarios administradores. 

los cambios se suben a la rama 11, para pruebas intensivas y se retoma el punto del presupuesto en pdf.

validar y cerrar el issue
