### ISSUE TITLE
Ajustes de tablas de items y budgets

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#17]
Se necesita: 
- incluir un campo activo dentro de las tablas de items y budgets, 
- ajustar las consultas para que en la vista de creacion de presupuesto traiga los items activos.

No se creara metodos para activar o desactivar, debe por su misma peticion put agregar el campo para actualizar ese estado.

**Comment by Martalf** [comment]
para la tabla items se agregó el campo de apiaudiophoneitems_status que solo puede tener dos posibles valores: ACTIVO  e INACTIVO
al momento de crear un item debes incluir el campo en el body de la peticion el campo del estatus con el valor activo: ejemplo:

{
    "apiaudiophoneitems_id" : 14,
    "apiaudiophoneitems_status" : "INACTIVO"
}

la ruta a la cual debes hacer la petición es esta:
apiaudiophoneitemstatus/update/10

**Comment by Martalf** [comment]
para la tabla budget se agregó el campo de apiaudiophonebudgets_status que solo puede tener dos posibles valores: PAGADO, PENDIENTE, NO_APLICA.

NO_APLICA, es un estatus que se agrega por si se genera un presupuesto por error de usuario, ejemplo coloca un monto que no es y se imprime, el usuario debe dejar ese registro como no aplica...

al momento de crear un budget debes incluir el campo en el body de la petición el campo del estatus con el valor activo: ejemplo:
{
    "apiaudiophonebudgets_id" : 1,
    "apiaudiophonebudgets_status" : "NO_APLICA"
}

la ruta a la cual debes hacer la petición es esta:
apiaudiophonebudgetstatus/update/10

**Comment by Martalf** [comment]
al momento de crear un nuevo budget e item debes incluir el campo en la peticion. ya que lo tengo como regla requerida en el request:

para budgets:
$this->validate($request, [

			'apiaudiophonebudgets_id_service' => 'required|numeric|between:1,2',
			'apiaudiophonebudgets_nameservice' => 'required|string|min:1|max:60',
			'apiaudiophonebudgets_client_name' => 'required|string|min:1|max:60',
			'apiaudiophonebudgets_client_email' => 'required|email|min:1|max:60',
			'apiaudiophonebudgets_client_phone' => 'required|string|min:1|max:60',
			'apiaudiophonebudgets_client_social' => 'required|string|min:1|max:60',
			'apiaudiophonebudgets_total_price' => 'required|numeric|regex:/^\d+(\.\d{1,2})?$/',
			_**'apiaudiophonebudgets_status' => 'required|regex:([A-Z])',**_
			'apiaudiophonebudgets_items' => 'required|array',
			'apiaudiophonebudgets_items.*' => 'required|array',
			'apiaudiophonebudgets_items.*.apiaudiophonebudgets_items_quantity' => 'required|numeric',
			'apiaudiophonebudgets_items.*.apiaudiophonebudgets_items_description' => 'required|string',
			'apiaudiophonebudgets_items.*.apiaudiophonebudgets_items_unit_price' => 'required|numeric|regex:/^\d+(\.\d{1,2})?$/',
			'apiaudiophonebudgets_items.*.apiaudiophonebudgets_items_subtotal' => 'required|numeric|regex:/^\d+(\.\d{1,2})?$/'
		]);


para items:

$this->validate($request, [

			'apiaudiophoneitems_name' => 'required|string|min:1|max:60',
			'apiaudiophoneitems_description' => 'required|string|min:1|max:60',
			'apiaudiophoneitems_price' => 'required|numeric|regex:/^\d+(\.\d{1,2})?$/',
			**_'apiaudiophoneitems_status' => 'required|regex:([A-Z])',_**
		]);

**Comment by Martalf** [comment]
por favor proceder a realizar las adecuaciones correspondientes en el front, los cambios se encuentran en la rama 11

**Comment by gabmart1995** [comment]
ajustar el metodo showApiaudiophoneItem y showApiaudiophoneBudget ambos no incluyen el campo status solicitado  en la respuesta para maquetar en la tabla.

![Captura de pantalla_2021-01-11_22-11-04](https://user-images.githubusercontent.com/30984939/104260450-eb36ed00-5459-11eb-9812-8b2e36b7adc0.png)
![Captura de pantalla_2021-01-11_22-10-47](https://user-images.githubusercontent.com/30984939/104260453-ebcf8380-5459-11eb-8766-fed173e896b6.png)
