### ISSUE TITLE
desarrollo de crud de user

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#2]
se necesita el desarrollo del crud de usuarios dentro de la aplicacion.

Importante: documentar el modelo de rutas del modelo y realizacion de pruebas.

**Comment by Martalf** [comment]
se crean rutas show, store, update y destroy... falta ajustar el crud de acuerdo a las siguientes reglas del negocio:

el user_role o admin_role puede modificar sus datos basicos como nombre, correo de acceso y contraseña. pero los datos de acceso como el status y el tipo de usuario lo hace el administador

cada usuario tiene una pagina de perfil que pueden modificar datos basicos en gestion de usuarios puede modificar los accesos siendo admin.

se estan desarrollando las validaciones en lumen

**Comment by Martalf** [comment]
sigue en mismo estatus, se pretende desarrollar un controller que apunte a inactivar el usuario cambiando el estatus del mismo.

**Comment by Martalf** [comment]
se adecua el método show para hacer busquedas por string. Validado con postman

**Comment by Martalf** [comment]
se cierra issue, se culmina de forma satisfactoria el CRUD de los usuarios, se trabaja en el issue de activar e inactivar usuarios dentro del user controller.
