### ISSUE TITLE
Generar documentacion del API

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#20]
Se necesita generar la documentacion del API:

- Requisitos minimos para correr la API.

- Migraciones de BD.

- Descripcion del proceso del endpoints, protocolos utilizados, cargas y respuestas del servidor. Recomendacion puedes generar esa informacion por postman.

- Descripcion para desplegar en entorno de desarrollo y producción.

- Bitacora de desarrollo (opcional), problemas observados dentro de la API, que se pueden mejorar, con el objetivo en que en el futuro, se puedan solventar.

**Comment by Martalf** [comment]
se estan realizando los pasos para describir el proceso de instalación en producción.
