### ISSUE TITLE
despliuegue de produccion en oficina

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#23]
Se desplegara el API en la oficina del jefe en el estudio, se procedera a instalacion de teamviever en el equipo de la oficina, para soporte remoto.

- Se debe instalar y configuar apache y php en ubuntu
- bajar el repositorio de la app completo y configurar mod_rewrite
- configurar base de datos de la aplicacion.
- tener disponible el frontend en el equipo

Se ejecutara la aplicacion dentro de la red interna en la maquina de la oficina

**Comment by Martalf** [comment]
aca estan pendiente la instalación de debian 11 de 32 bit en la máquina para instalar la app...

**Comment by gabmart1995** [comment]
se instalo la app en debian 11 en 32 bits, se procedera a bajar e instalar en sistema en prod.

- Instalar debian 11 ( actualiemente en este paso )
- configurar php 7.4
- desplegauar el core y api
