### ISSUE TITLE
creacion de factories de user

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#3]
se necesita que la base de datos pueda generar 15 usuarios de prueba, para desarrollo y pruebas frontend

**Comment by Martalf** [comment]
se cierra este issue ya que se generóel factory para crear usuarios de manera automatica... si se desea cambiar la cantidad de usuarios a 15... realizar la siguiente modificación en el archivo ApiAudiophoneUserSeeder.php, en la siguiente linea de instruccion:

factory(ApiAudiophoneUser::class, **14**)->create();

quedo atento a cualquier comentario
