### ISSUE TITLE
habilitar cors en la aplicacion

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#4]
habilitar el cors ( peticiones de origen cruzado ) de laravel lumien, para que pueda recibir peticiones desde frontend.

**Comment by Martalf** [comment]
se configuró laravel lumen para recibir peticiones desde un servidor frontend distinto al de laravel, la solucion esta en el siguiente link: https://github.com/fruitcake/laravel-cors#lumen

ejecutas el comando:
composer require fruitcake/laravel-cors

luego configuras el archivo bootstrap.php
creas una carpeta config en lumen y creas un archivo cors.php donde copias y pegas el contenido del archivo cors, del service provider, y listo.

detalle de las instrucciones en el link del comentario
