### ISSUE TITLE
desarrollo de autheticacion en laravel

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#5]
se necesita de un sistema que permita autenticar el usuario de la aplicacion, que permita identificar si el usuario es valido sino que devuelva un 401.

**Comment by Martalf** [comment]
pendiente por empezar, se pretende implementar laravel passport, autenticación mediante tokens, se evaluará otra opción que es el uso de jwt.

**Comment by gabmart1995** [comment]
Cuando el usuario para el proceso de authenticación con éxito el servidor, debe devolver el estatus y sus datos básicos del usuario que son: id, nombre del usuario, correo, rol y token de usuario para realizar las peticiones. Siendo usados para realizar las consultas de forma segura las recursos al api. Un ejemplo sencillo es la modificacion del usuario en la vista de profile, se necesita de los datos del usuario authenticado para realizar actualizaciones de sus datos.
