### ISSUE TITLE
Desarrollo de metodos cambio de rol, consultar usuarios inactivos y reactivar un usuario

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#6]
Se necesita de la creacion de metodos dentro de controlador de usuarios que permita, el cambio de rol ( el json contendra solo el role del usuario que le manda ). Un metodo que permite consultar los usuarios registrados inactivos y otro para restaurarlos.

**Comment by Martalf** [comment]
el metodo cambio de rol se actualizo en el método update user, se trabaja en los métodos de activar e inactivar usuarios.

**Comment by Martalf** [comment]
se realizaron los métodos de inactivar y reactivar los usuarios así como el de cambiar el role de usuarios.

**Comment by Martalf** [comment]
avisame si tu vas a realizar una vista para listar solo usuarios activos y otra vista para listar usuarios inactivos. voy a dejar el issue abierto
