### ISSUE TITLE
Corrección en metodo de actualizacion de usuarios 

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#7]
Para la actualizacion del perfil del usuario solamente se necesitan que los campos del nombre y correo electronico sean requeridos, el password  debe ser opcional. Puede suceder que el usuario solo necesite que cambie su nombre o correo sin cambiar su contraseña.

 **Ojo:** los metodos de cambio de rol y cambio de estatus, se agregaran en otro metodo dentro del controlador.

la peticion al servidor queda de la siguiente manera:

body { 
.apiaudiophoneusers_fullname: string,
.apiaudiophoneusers_email: string,
.apiaudiophoneusers_password?: string   // opcional
 }
todo con su id dentro de la url. como lo has  estado trabajando

**Comment by Martalf** [comment]
se adecua el método de update user, se probo en la aplicación y se probó por postman, se cierra issue
