### ISSUE TITLE
Creacion del modelo de terms

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#8]
Se necesita la creacion de un modelo de CRUD para la seccion de terminos. Esta seccion sera la encargada de gestionar la solcitud de eventos generadas por la aplicación.

![terms](https://user-images.githubusercontent.com/30984939/83944145-44a5b200-a7cf-11ea-8d14-504fc4764aa0.png)

### objetivos
- el administador debe poder configurar los parametros de creacion de eventos. Tanto para grabacion, como para alquiler.
- tener log de quien creo o modifico los terminos de servicio.
- se debe hacer la relacion con la tabla services para identificar a cual servicio pertenece.
- implementar el middleware de auth en esa ruta.

**Comment by Martalf** [comment]
modelo y controlador funcionales.

metodos funcionales, solo show y store.
métodos que no se encuentran activos , update y destroy.

pruebas hechas con postman culminadas. 

falta pruebas entre front y back

**Comment by Martalf** [comment]
modelo culminado, falta nuevamete hacer las pruebas donde se trae el nombre del servicio a actualizar
