### ISSUE TITLE
Crear modelo services y crear factory

### ISSUE THREAD

**Issue by gabmart1995** [eaudiophone/apiaudiophone#9]
Se necesita crear un factory para la tabla BD de servicios que será la responsable de relacionar los eventos y terminos de servicios.

datos a colocar en el factory:

idServices: 1
nameService: 'alquiler',
description: 'alquiler de equipos de sonido profesional'

idServices: 2
nameService: 'grabacion',
descripcion: 'grabacion de piezas musicales'

**Comment by Martalf** [comment]
se creo el modelo services y su relacion con terms, las consultas directamente en laravel funcionan correctamente. el Factory solo se puede agregar un solo tipo de llenado de tabla y con el seeder le indicas cuantas veces se va a repetir, lo que se hara sera que el factory llene uno y el seeder el otro registro, que de echo ya se hizo asi que por este lado estamos listos
